spring:
  config:
    import: optional:file:.env[.properties]

okta:
  oauth2:
    ISSUER: ${AUTH_ISSUER}
    CLIENT_ID: ${AUTH_CLIENT_ID}
    CLIENT_SECRET: ${AUTH_CLIENT_SECRET}

  cloudinary:
    CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
    API_KEY: ${CLOUDINARY_API_KEY}
    API_SECRET: ${CLOUDINARY_API_SECRET}

spotify:
  CLIENT_ID: ${SPOTIFY_CLIENT_ID}
  CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
  AUTHORIZE_URL: ${SPOTIFY_AUTHORIZE_URL}
  TOKEN_URL: ${SPOTIFY_TOKEN_URL}
  API_BASE_URL: ${SPOTIFY_API_BASE_URL}
  REDIRECT_URI: ${SPOTIFY_REDIRECT_URL}



